src/OneBeyond.Studio.Application.SharedKernel.Tests/SomeAggregateRoot.cs
src/OneBeyond.Studio.Application.SharedKernel/CommandHandlers/CreateHandler.cs
src/OneBeyond.Studio.Application.SharedKernel/CommandHandlers/DeleteHandler.cs
src/OneBeyond.Studio.Application.SharedKernel/CommandHandlers/UpdateHandler.cs
src/OneBeyond.Studio.Application.SharedKernel/Repositories/IRWRepository.cs
src/OneBeyond.Studio.Application.SharedKernel/Repositories/IRWRepositoryExtensions.cs
src/OneBeyond.Studio.DataAccess.EFCore.Tests/AggregateRootTests.cs
src/OneBeyond.Studio.DataAccess.EFCore.Tests/Data/Repositories/AggregateRootRWRepository.cs
src/OneBeyond.Studio.DataAccess.EFCore.Tests/Data/Repositories/RWRepository.cs
src/OneBeyond.Studio.DataAccess.EFCore.Tests/Entities/AirTravels/Company.cs
src/OneBeyond.Studio.DataAccess.EFCore.Tests/Entities/AirTravels/Survey.cs
src/OneBeyond.Studio.DataAccess.EFCore.Tests/Entities/PurchaseOrders/Account.cs
src/OneBeyond.Studio.DataAccess.EFCore.Tests/Entities/PurchaseOrders/Product.cs
src/OneBeyond.Studio.DataAccess.EFCore.Tests/Entities/PurchaseOrders/PurchaseOrder.cs
src/OneBeyond.Studio.DataAccess.EFCore.Tests/Entities/PurchaseOrders/PurchaseOrderLine.cs
src/OneBeyond.Studio.DataAccess.EFCore.Tests/Entities/PurchaseOrders/Vendor.cs
src/OneBeyond.Studio.DataAccess.EFCore.Tests/Entities/PurchaseOrders/Vendors.cs
src/OneBeyond.Studio.DataAccess.EFCore.Tests/TestsBase.cs
src/OneBeyond.Studio.DataAccess.EFCore/Repositories/BaseRWRepository.cs
src/OneBeyond.Studio.Domain.SharedKernel/Entities/AggregateRoot.cs
src/OneBeyond.Studio.Domain.SharedKernel/Entities/Commands/Create.cs
src/OneBeyond.Studio.Domain.SharedKernel/Entities/Commands/Delete.cs
src/OneBeyond.Studio.Domain.SharedKernel/Entities/Commands/Update.cs
src/OneBeyond.Studio.Domain.SharedKernel/Entities/IAggregateRoot.cs

IAggregateRoot replaced with AggregateRoot abstract class. 
AggregateRoot tests added.
Note, It is a breaking change!

IAggregateRoot replacement

---

src/OneBeyond.Studio.Application.SharedKernel/OneBeyond.Studio.Application.SharedKernel.csproj
src/OneBeyond.Studio.DataAccess.EFCore/OneBeyond.Studio.DataAccess.EFCore.csproj
src/OneBeyond.Studio.Hosting/OneBeyond.Studio.Hosting.csproj

Redundant dependencies removed

Dependencies fixes

---

src/OneBeyond.Studio.Application.SharedKernel/Specifications/FilterExpressionBuilder.cs

Unused private member removed

---

src/OneBeyond.Studio.EntityAuditing/OneBeyond.Studio.EntityAuditing.Infrastructure/AuditDataProvider.cs

Sonar fixes

---

src/OneBeyond.Studio.Hosting.AspNet/Http/HttpContextAccessorExtensions.cs

- Added `TryGetUserClaimValue` to `HttpContextAccessorExtensions`
- Replaced `GetUserAuthId` (kept as obsolete) with `GetUserClaimValue`

Added TryGetUserClaimValue to HttpContextAccessorExtensions

---

src/OneBeyond.Studio.Application.SharedKernel/CommandHandlers/CreateHandler.cs
src/OneBeyond.Studio.Application.SharedKernel/CommandHandlers/UpdateHandler.cs
src/OneBeyond.Studio.Domain.SharedKernel/Entities/Commands/Create.cs
src/OneBeyond.Studio.Domain.SharedKernel/Entities/Commands/Update.cs

Marked Create and Update commands as obsolete

Marked Create and Update commands as obsolete

---

src/OneBeyond.Studio.Crosscuts/OneBeyond.Studio.Crosscuts.csproj
src/OneBeyond.Studio.Hosting.AspNet/OneBeyond.Studio.Hosting.AspNet.csproj

Serilog updated to 3.0.1

---

src/OneBeyond.Studio.EntityAuditing/OneBeyond.Studio.EntityAuditing.Domain/AuditEvent.cs
src/OneBeyond.Studio.EntityAuditing/OneBeyond.Studio.EntityAuditing.Domain/IAuditContext.cs
src/OneBeyond.Studio.EntityAuditing/OneBeyond.Studio.EntityAuditing.Infrastructure/AuditDataProvider.cs
src/OneBeyond.Studio.EntityAuditing/OneBeyond.Studio.EntityAuditing.SqlServer/AuditDbWriter.cs
src/OneBeyond.Studio.EntityAuditing/OneBeyond.Studio.EntityAuditing.SqlServer/Configuration/AuditEventConfiguration.cs
src/OneBeyond.Studio.EntityAuditing/OneBeyond.Studio.EntityAuditing.SqlServer/Entities/AuditEvent.cs
src/OneBeyond.Studio.EntityAuditing/OneBeyond.Studio.EntityAuditing.SqlServer/Migrations/20200403113204_InitialMigration.Designer.cs
src/OneBeyond.Studio.EntityAuditing/OneBeyond.Studio.EntityAuditing.SqlServer/Migrations/20200403113204_InitialMigration.cs
src/OneBeyond.Studio.EntityAuditing/OneBeyond.Studio.EntityAuditing.SqlServer/Migrations/AuditDbContextModelSnapshot.cs

1. AuditEvent, Id property made long (and the corresponding SQL table column is bigint)
2. AuditEvent, Context property added (to store the context, in which the audit event happened)
3. IAuditContext, Context added

Audit extensions

---

src/OneBeyond.Studio.Application.SharedKernel.Tests/OneBeyond.Studio.Application.SharedKernel.Tests.csproj
src/OneBeyond.Studio.Application.SharedKernel/OneBeyond.Studio.Application.SharedKernel.csproj
src/OneBeyond.Studio.Crosscuts.Tests/OneBeyond.Studio.Crosscuts.Tests.csproj
src/OneBeyond.Studio.DataAccess.EFCore.Tests/OneBeyond.Studio.DataAccess.EFCore.Tests.csproj
src/OneBeyond.Studio.DataAccess.EFCore/OneBeyond.Studio.DataAccess.EFCore.csproj
src/OneBeyond.Studio.Domain.SharedKernel/OneBeyond.Studio.Domain.SharedKernel.csproj
src/OneBeyond.Studio.EntityAuditing/OneBeyond.Studio.EntityAuditing.Infrastructure/OneBeyond.Studio.EntityAuditing.Infrastructure.csproj
src/OneBeyond.Studio.Hosting.AspNet.Tests/OneBeyond.Studio.Hosting.AspNet.Tests.csproj
src/OneBeyond.Studio.Hosting.AspNet/OneBeyond.Studio.Hosting.AspNet.csproj
src/OneBeyond.Studio.Hosting.Tests/OneBeyond.Studio.Hosting.Tests.csproj
src/OneBeyond.Studio.Infrastructure.Azure.Tests/OneBeyond.Studio.Infrastructure.Azure.Tests.csproj
src/OneBeyond.Studio.Infrastructure.Azure/OneBeyond.Studio.Infrastructure.Azure.csproj

3rd party libs update

---

src/OneBeyond.Studio.Application.SharedKernel.Tests/OneBeyond.Studio.Application.SharedKernel.Tests.csproj
src/OneBeyond.Studio.Application.SharedKernel/OneBeyond.Studio.Application.SharedKernel.csproj
src/OneBeyond.Studio.Crosscuts.Tests/OneBeyond.Studio.Crosscuts.Tests.csproj
src/OneBeyond.Studio.DataAccess.EFCore.Tests/OneBeyond.Studio.DataAccess.EFCore.Tests.csproj
src/OneBeyond.Studio.DataAccess.EFCore/OneBeyond.Studio.DataAccess.EFCore.csproj
src/OneBeyond.Studio.EntityAuditing/OneBeyond.Studio.EntityAuditing.AzureTableStorage/OneBeyond.Studio.EntityAuditing.AzureTableStorage.csproj
src/OneBeyond.Studio.EntityAuditing/OneBeyond.Studio.EntityAuditing.Infrastructure/OneBeyond.Studio.EntityAuditing.Infrastructure.csproj
src/OneBeyond.Studio.Hosting.AspNet.Tests/OneBeyond.Studio.Hosting.AspNet.Tests.csproj
src/OneBeyond.Studio.Hosting.AspNet/OneBeyond.Studio.Hosting.AspNet.csproj
src/OneBeyond.Studio.Hosting.Tests/OneBeyond.Studio.Hosting.Tests.csproj
src/OneBeyond.Studio.Infrastructure.Azure.Tests/OneBeyond.Studio.Infrastructure.Azure.Tests.csproj
src/OneBeyond.Studio.Infrastructure.Azure/OneBeyond.Studio.Infrastructure.Azure.csproj

Third party libs update

---

src/OneBeyond.Studio.Application.SharedKernel.Tests/OneBeyond.Studio.Application.SharedKernel.Tests.csproj
src/OneBeyond.Studio.Crosscuts.Tests/OneBeyond.Studio.Crosscuts.Tests.csproj
src/OneBeyond.Studio.DataAccess.EFCore.Tests/OneBeyond.Studio.DataAccess.EFCore.Tests.csproj
src/OneBeyond.Studio.DataAccess.EFCore/OneBeyond.Studio.DataAccess.EFCore.csproj
src/OneBeyond.Studio.EntityAuditing/OneBeyond.Studio.EntityAuditing.Infrastructure/OneBeyond.Studio.EntityAuditing.Infrastructure.csproj
src/OneBeyond.Studio.Hosting.AspNet.Tests/OneBeyond.Studio.Hosting.AspNet.Tests.csproj
src/OneBeyond.Studio.Hosting.AspNet/OneBeyond.Studio.Hosting.AspNet.csproj
src/OneBeyond.Studio.Infrastructure.Azure/OneBeyond.Studio.Infrastructure.Azure.csproj

Third party libraries updated

---

src/OneBeyond.Studio.Crosscuts.Tests/FileUploadValidators.cs
src/OneBeyond.Studio.Crosscuts/Utilities/FileUploadValidators/FileSizeValidatorException.cs
src/OneBeyond.Studio.Crosscuts/Utilities/FileUploadValidators/FileValidatorBuilder.cs

Added File Size validation on FileValidatorBuilder to be able to check whether the file size is greater than a number of bytes.

Added File Size validation on FileValidatorBuilder

---

Directory.Packages.props
OneBeyond.Studio.Core.sln
src/Directory.Build.props
src/OneBeyond.Studio.Application.SharedKernel.Tests/OneBeyond.Studio.Application.SharedKernel.Tests.csproj
src/OneBeyond.Studio.Application.SharedKernel/OneBeyond.Studio.Application.SharedKernel.csproj
src/OneBeyond.Studio.Crosscuts.Tests/OneBeyond.Studio.Crosscuts.Tests.csproj
src/OneBeyond.Studio.Crosscuts/OneBeyond.Studio.Crosscuts.csproj
src/OneBeyond.Studio.DataAccess.EFCore.Tests/OneBeyond.Studio.DataAccess.EFCore.Tests.csproj
src/OneBeyond.Studio.DataAccess.EFCore/OneBeyond.Studio.DataAccess.EFCore.csproj
src/OneBeyond.Studio.Domain.SharedKernel/OneBeyond.Studio.Domain.SharedKernel.csproj
src/OneBeyond.Studio.EntityAuditing/OneBeyond.Studio.EntityAuditing.AzureTableStorage/OneBeyond.Studio.EntityAuditing.AzureTableStorage.csproj
src/OneBeyond.Studio.EntityAuditing/OneBeyond.Studio.EntityAuditing.Infrastructure/OneBeyond.Studio.EntityAuditing.Infrastructure.csproj
src/OneBeyond.Studio.EntityAuditing/OneBeyond.Studio.EntityAuditing.SqlServer/OneBeyond.Studio.EntityAuditing.SqlServer.csproj
src/OneBeyond.Studio.Hosting.AspNet.Tests/OneBeyond.Studio.Hosting.AspNet.Tests.csproj
src/OneBeyond.Studio.Hosting.AspNet/OneBeyond.Studio.Hosting.AspNet.csproj
src/OneBeyond.Studio.Hosting.Tests/OneBeyond.Studio.Hosting.Tests.csproj
src/OneBeyond.Studio.Hosting/OneBeyond.Studio.Hosting.csproj
src/OneBeyond.Studio.Infrastructure.Azure.Tests/OneBeyond.Studio.Infrastructure.Azure.Tests.csproj
src/OneBeyond.Studio.Infrastructure.Azure/OneBeyond.Studio.Infrastructure.Azure.csproj
src/OneBeyond.Studio.Infrastructure.RabbitMQ/OneBeyond.Studio.Infrastructure.RabbitMQ.csproj

Introduced the concept of centralized Nuget packages management to manage all versions of Nuget packages in one place.
https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management
Better management of multiple projects

Implemented Central Package Management (CPM)

---

src/OneBeyond.Studio.EntityAuditing/OneBeyond.Studio.EntityAuditing.SqlServer/AuditEventRepository.cs

Use SchemaQualifiedTableName for bulk Audit

---

src/OneBeyond.Studio.EntityAuditing/OneBeyond.Studio.EntityAuditing.SqlServer/AuditBulkDbWriter.cs
src/OneBeyond.Studio.EntityAuditing/OneBeyond.Studio.EntityAuditing.SqlServer/AuditDbWriter.cs

Audit bug fixes

---

src/OneBeyond.Studio.EntityAuditing/OneBeyond.Studio.EntityAuditing.SqlServer/AuditBulkDbWriter.cs

Bulk Audit fixes

---

src/OneBeyond.Studio.EntityAuditing/OneBeyond.Studio.EntityAuditing.Infrastructure/AuditDataProvider.cs

Audit bulk fixes

---

src/OneBeyond.Studio.EntityAuditing/OneBeyond.Studio.EntityAuditing.Domain/IAuditBulkWriter.cs
src/OneBeyond.Studio.EntityAuditing/OneBeyond.Studio.EntityAuditing.SqlServer/AuditBulkDbWriter.cs
src/OneBeyond.Studio.EntityAuditing/OneBeyond.Studio.EntityAuditing.SqlServer/AuditDbConverter.cs
src/OneBeyond.Studio.EntityAuditing/OneBeyond.Studio.EntityAuditing.SqlServer/AuditDbConverterFactory.cs

AuditDbConverterFactory added

---

src/OneBeyond.Studio.EntityAuditing/OneBeyond.Studio.EntityAuditing.SqlServer/AuditDbConverterFactory.cs

Audit fixes

---

Directory.Packages.props
src/OneBeyond.Studio.Application.SharedKernel.Tests/OneBeyond.Studio.Application.SharedKernel.Tests.csproj
src/OneBeyond.Studio.Application.SharedKernel/OneBeyond.Studio.Application.SharedKernel.csproj
src/OneBeyond.Studio.Crosscuts.Tests/OneBeyond.Studio.Crosscuts.Tests.csproj
src/OneBeyond.Studio.Crosscuts/OneBeyond.Studio.Crosscuts.csproj
src/OneBeyond.Studio.DataAccess.EFCore.Tests/OneBeyond.Studio.DataAccess.EFCore.Tests.csproj
src/OneBeyond.Studio.DataAccess.EFCore/OneBeyond.Studio.DataAccess.EFCore.csproj
src/OneBeyond.Studio.Domain.SharedKernel/OneBeyond.Studio.Domain.SharedKernel.csproj
src/OneBeyond.Studio.EntityAuditing/OneBeyond.Studio.EntityAuditing.AzureTableStorage/OneBeyond.Studio.EntityAuditing.AzureTableStorage.csproj
src/OneBeyond.Studio.EntityAuditing/OneBeyond.Studio.EntityAuditing.Domain/OneBeyond.Studio.EntityAuditing.Domain.csproj
src/OneBeyond.Studio.EntityAuditing/OneBeyond.Studio.EntityAuditing.Infrastructure/OneBeyond.Studio.EntityAuditing.Infrastructure.csproj
src/OneBeyond.Studio.EntityAuditing/OneBeyond.Studio.EntityAuditing.SqlServer/OneBeyond.Studio.EntityAuditing.SqlServer.csproj
src/OneBeyond.Studio.Hosting.AspNet.Tests/OneBeyond.Studio.Hosting.AspNet.Tests.csproj
src/OneBeyond.Studio.Hosting.AspNet/OneBeyond.Studio.Hosting.AspNet.csproj
src/OneBeyond.Studio.Hosting.Tests/OneBeyond.Studio.Hosting.Tests.csproj
src/OneBeyond.Studio.Hosting/OneBeyond.Studio.Hosting.csproj
src/OneBeyond.Studio.Infrastructure.Azure.Tests/OneBeyond.Studio.Infrastructure.Azure.Tests.csproj
src/OneBeyond.Studio.Infrastructure.Azure/OneBeyond.Studio.Infrastructure.Azure.csproj
src/OneBeyond.Studio.Infrastructure.RabbitMQ/OneBeyond.Studio.Infrastructure.RabbitMQ.csproj

.NET 8 migration

---

src/Directory.Build.props

DotNetVersion fix
